config/routes.rb
Dotplus::Application.routes.draw do

  root to: 'pages#home', constraints: { subdomain: /www|^$/ }
  root to: 'events#index', constraints: { subdomain: /.+/ }, as: :next_event

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :sponsors
    resources :users
    resources :locations
  end

  get 'auth/twitter/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'logout' => 'sessions#destroy'

  resources :sponsors
  resources :talks
  resources :events do
    resources :posts
    resources :attendees do
      collection do
        get :rsvp
      end
    end
  end
  resources :users, path: '/' do
    resources :posts
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :city
  belongs_to :sponsor
  belongs_to :organizer, class_name: "User"
  belongs_to :location
  belongs_to :beginner_talk, class_name: "Talk"
  belongs_to :advanced_talk, class_name: "Talk"
  has_one :beginner_speaker, through: :beginner_talk, source: :user
  has_one :advanced_speaker, through: :advanced_talk, source: :user
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
  has_many :posts, as: :postable

  scope :by_date, -> { order(:start) }

  def to_param
    "#{id} #{start.to_date}".parameterize
  end

  def schedule
    [
      { what: "Mingle", time: start },
      { what: beginner_talk.try(:title) || "Beginner Talk", time: (start + 15.minutes), user: beginner_talk.try(:user) },
      { what: advanced_talk.try(:title) || "Advanced Talk", time: (start + 30.minutes), user: advanced_talk.try(:user) },
      { what: "Hack", time: (start + 75.minutes) },
      { what: "Bar", time: self.end },
    ]
  end

  def description
    date = start.strftime('%A, %b %d')
    if advanced_talk || beginner_talk
      desc = "On #{date}, #{(advanced_talk || beginner_talk).user.name} will present his talk \"#{(advanced_talk || beginner_talk).title}\""
    else
      desc = "On #{date}, a group of mobile/web/hardware developers will meet to teach each other cool stuff."
    end

    desc = desc + " at #{location.name}" if location

    desc
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < BaseController
    def index
      @events = current_city.events
    end

    def show
      @event = Event.find(params[:id])

      respond_to do |format|
        format.html
        format.pdf do
          pdf = EventPdf.new(@event)
          send_data pdf.render, filename: "event",
            type: "application/pdf",
            disposition: "inline"
        end
      end
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)
      @event.city = current_city
      if @event.save
        flash[:success] = "Created event"
        redirect_to admin_event_path(@event)
      else
        render :new
      end
    end

    def edit
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])
      if @event.update_attributes(event_params)
        flash[:success] = "Updated event"
        redirect_to admin_event_path(@event)
      else
        render :edit
      end
    end

    private
    def event_params
      params.require(:event).permit(:start, :end, :sponsor_id, :organizer_id, :food, :beginner_talk_id, :advanced_talk_id)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    event = current_city.events.order('start').last
    if event
      redirect_to event_path(event)
    else
      render :no_event
    end
  end

  def show
    @event = current_city.events.includes(:attendees).find_by_id(params[:id])
    return redirect_to root_path unless @event
    @attending = @event.attendees.include?(current_user)
  end
end

app/views/admin/events/edit.html.haml
.row
  .columns.large-6
    = simple_form_for @event, url: admin_event_path(@event) do |f|
      %fieldset
        %legend Edit Event
        .row
          .columns.large-6
            = f.input       :start
          .columns.large-6
            = f.input       :end
        .row
          .columns.large-6
            = f.association :sponsor
          .columns.large-6
            = link_to "New Sponsor", new_admin_sponsor_path
        .row
          .columns.large-6
            = f.association :organizer, label: "Organizer's Twitter Handle"
        .row
          .columns.large-6
            = f.association :beginner_talk
          .columns.large-6
            = f.association :advanced_talk
        .row
          .columns.large-12
            = f.input       :food
        = f.button      :submit

app/views/admin/events/index.html.haml
.row
  .columns
    %h2 #{current_city.name} Events
    = link_to "New Event", new_admin_event_path, class: 'button'
    %ul
      - @events.each do |event|
        %li= link_to event.start.to_date, admin_event_path(event)

app/views/admin/events/new.html.haml
.row
  .columns.large-6
    = simple_form_for @event, url: admin_events_path do |f|
      %fieldset
        %legend New Event
        .row
          .columns.large-6
            = f.input       :start
          .columns.large-6
            = f.input       :end
        .row
          .columns.large-6
            = f.association :sponsor
          .columns.large-6
            = link_to "New Sponsor", new_admin_sponsor_path
        .row
          .columns.large-6
            = f.association :organizer, label: "Organizer's Twitter Handle"
        .row
          .columns.large-12
            = f.input       :food
        = f.button      :submit

app/views/admin/events/show.html.haml
.row
  .columns
    %h2= @event.start.to_date
    %p
      %strong Start:
      = @event.start
    %p
      %strong End:
      = @event.end
    %p
      %strong Sponsor:
      - if @event.sponsor
        = link_to @event.sponsor.name, admin_sponsor_path(@event.sponsor)
      - else
        TBD
    %p
      %strong Location:
      - if @event.location
        = link_to @event.location.name, admin_location_path(@event.location)
      - else
        TBD
    %p
      %strong Organizer:
      - if @event.organizer
        = link_to @event.organizer.name, admin_user_path(@event.organizer)
      - else
        TBD
    %p
      %strong Beginner Talk:
      - if @event.beginner_talk
        = @event.beginner_talk.title
      - else
        TBD
    %p
      %strong Advanced Talk:
      - if @event.advanced_talk
        = @event.advanced_talk.title
      - else
        TBD
    = link_to "Edit", edit_admin_event_path(@event), class: 'button'
    = link_to "View on site", event_path(@event), class: 'button'
    = link_to "Nametags", admin_event_path(@event, format: 'pdf'), class: 'button'