config/routes.rb
Dotplus::Application.routes.draw do

  root to: 'pages#home', constraints: { subdomain: /www|^$/ }
  root to: 'events#index', constraints: { subdomain: /.+/ }, as: :next_event

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :sponsors
    resources :users
    resources :locations
  end

  get 'auth/twitter/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'logout' => 'sessions#destroy'

  resources :sponsors
  resources :talks
  resources :events do
    resources :posts
    resources :attendees do
      collection do
        get :rsvp
      end
    end
  end
  resources :users, path: '/' do
    resources :posts
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :city
  belongs_to :sponsor
  belongs_to :organizer, class_name: "User"
  belongs_to :location
  belongs_to :beginner_talk, class_name: "Talk"
  belongs_to :advanced_talk, class_name: "Talk"
  has_one :beginner_speaker, through: :beginner_talk, source: :user
  has_one :advanced_speaker, through: :advanced_talk, source: :user
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
  has_many :posts, as: :postable

  scope :by_date, -> { order(:start) }

  def to_param
    "#{id} #{start.to_date}".parameterize
  end

  def schedule
    [
      { what: "Mingle", time: start },
      { what: beginner_talk.try(:title) || "Beginner Talk", time: (start + 15.minutes), user: beginner_talk.try(:user) },
      { what: advanced_talk.try(:title) || "Advanced Talk", time: (start + 30.minutes), user: advanced_talk.try(:user) },
      { what: "Hack", time: (start + 75.minutes) },
      { what: "Bar", time: self.end },
    ]
  end

  def description
    date = start.strftime('%A, %b %d')
    if advanced_talk || beginner_talk
      desc = "On #{date}, #{(advanced_talk || beginner_talk).user.name} will present his talk \"#{(advanced_talk || beginner_talk).title}\""
    else
      desc = "On #{date}, a group of mobile/web/hardware developers will meet to teach each other cool stuff."
    end

    desc = desc + " at #{location.name}" if location

    desc
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < BaseController
    def index
      @events = current_city.events
    end

    def show
      @event = Event.find(params[:id])

      respond_to do |format|
        format.html
        format.pdf do
          pdf = EventPdf.new(@event)
          send_data pdf.render, filename: "event",
            type: "application/pdf",
            disposition: "inline"
        end
      end
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)
      @event.city = current_city
      if @event.save
        flash[:success] = "Created event"
        redirect_to admin_event_path(@event)
      else
        render :new
      end
    end

    def edit
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])
      if @event.update_attributes(event_params)
        flash[:success] = "Updated event"
        redirect_to admin_event_path(@event)
      else
        render :edit
      end
    end

    private
    def event_params
      params.require(:event).permit(:start, :end, :sponsor_id, :organizer_id, :food, :beginner_talk_id, :advanced_talk_id)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    event = current_city.events.order('start').last
    if event
      redirect_to event_path(event)
    else
      render :no_event
    end
  end

  def show
    @event = current_city.events.includes(:attendees).find_by_id(params[:id])
    return redirect_to root_path unless @event
    @attending = @event.attendees.include?(current_user)
  end
end

app/views/events/_talk.html.haml
- if defined? talk
  = image_tag talk.user.avatar
  .info
    %h4= talk.user.name
    %p
      = talk.user.bio
      - if talk.user.url
        &bull;
        = link_to talk.user.url
  %h4= talk.title
  %p= raw talk.description
  - if current_user == talk.user
    = link_to "Edit", edit_talk_path(talk), class: 'button'
- else
  %h4 We need a talk!
  = link_to "Suggest a talk", current_user ? new_talk_path : "/auth/twitter?redirect_to=#{new_talk_path}", class: 'button'

app/views/events/no_event.html.haml
.row
  .columns
    %p We're planning on starting a #{current_city.name} event soon.
    %p If you're interested in sponsoring, hosting or speaking, email Jeff Dickey at #{ link_to "jeff@dickey.xxx", mailto: 'mailto:jeff@dickey.xxx' }.
    - if current_user && current_user.cities.include?(current_city.subdomain)
      %p
        %strong You're receiving updates for #{current_city.name}
    - elsif current_user
      %p Sign up if you want to receive updates on any #{current_city.name} events.
      = form_for current_user do |f|
        = f.label :email, "Email"
        = f.text_field :email
        = f.hidden_field :city, value: current_city.subdomain
        = f.submit "Sign up", class: 'button'
    - else
      %p
        %strong
          = link_to "Sign up", "/auth/twitter"
          if you want to receive updates on any #{current_city.name} events.

app/views/events/show.html.haml
- content_for :facebook_meta do
  %meta{ property: "og:type", content: "dotplusio:event" }
  %meta{ property: "og:url", content: request.url }
  %meta{ property: "og:title", content: "dotplus_#{current_city.subdomain}" }
  - if @event.advanced_talk
    %meta{ property: "og:image", content: @event.advanced_talk.user.avatar }
  - else
    %meta{ property: "og:image", content: image_url('logo.png') }
  %meta{ property: "og:description", content: @event.description }

#event
  .main-info
    .row
      .large-4.columns
        %h3= @event.start.strftime('%A, %b %d')
        %h4= @event.start.strftime('%l:%M %p')
        %h5 Sponsor
        - if @event.sponsor
          %p= link_to @event.sponsor.name, sponsor_path(@event.sponsor)
        - else
          %p
            TBD
            %br/
            = link_to "Want to sponsor?", 'mailto:jeff@dickey.xxx'
        - if @event.food.present?
          %h5 Food
          %p= @event.food
        - if @event.organizer
          .organizer
            %h5 Organizer
            %p
              = link_to user_path(@event.organizer) do
                = image_tag @event.organizer.avatar
                @#{@event.organizer.name}
        %p.registration
          - if @attending
            %h5 You're registered!
            - if current_user.email.blank?
              = form_for current_user do |f|
                = f.label :email, "Would you mind leaving me your email?"
                = f.text_field :email
                = f.submit "Submit", class: 'button'
            = link_to "Cancel Reservation", event_attendee_path(@event, current_user), method: :delete
          - else
            = link_to "RSVP", current_user ? rsvp_event_attendees_path(@event) : "/auth/twitter?redirect_to=#{rsvp_event_attendees_url(@event)}", class: "large button expand round"
        .social
          .facebook
            .fb-like{ data: { href: event_url(@event), send: "false", layout: "button_count" } }
          %p.twitter
            - twitter_text = "a dev event for polyglots"
            - twitter_text = @event.advanced_talk.title if @event.advanced_talk
            %a.twitter-hashtag-button{ href: "https://twitter.com/intent/tweet?button_hashtag=dotplus_#{current_city.subdomain}&text=#{twitter_text}", data: { related: "dotplusio", url: request.url } } Tweet #dotplus_#{current_city.subdomain}
      .large-4.columns
        - if @event.location
          = link_to "http://maps.google.com/?q=#{@event.location.address}" do
            = image_tag "http://maps.googleapis.com/maps/api/staticmap?markers=#{@event.location.latitude},#{@event.location.longitude}&zoom=10&size=300x200&visual_refresh=true&sensor=false"
          %h4.subheader= @event.location.name
          %p= @event.location.notes
        - else
          %h4 Location TBD
          = link_to "Want to host?", 'mailto:jeff@dickey.xxx', class: 'small button'
      .large-4.columns
        %h4 Schedule
        %ul#schedule.no-bullet
          - @event.schedule.each do |e|
            %li
              - if e[:user]
                = image_tag e[:user].avatar
              - else
                = image_tag 'logo.png'
              .title= e[:what]
              .time= e[:time].strftime('%l:%M')
  #speaker-info
    .row
      .large-6.columns
        %h2 Beginner Speaker
        = render partial: "talk", object: @event.beginner_talk, as: :talk
      .large-6.columns
        %h2 Advanced Speaker
        = render partial: "talk", object: @event.advanced_talk, as: :talk
  - if @event.attendees.any?
    .row
      .large-12.columns
        %h3= pluralize(@event.attendees.count, "attendee")
        %ul.large-block-grid-10
          - @event.attendees.each do |user|
            %li
              = link_to user_path(user), class: 'attendee-photo' do
                = image_tag user.avatar
                .handle= "@#{user.twitter}"
  .posts
    .row
      .columns
        %h3 Event Wall
        - if current_user
          = simple_form_for Post.new, url: event_posts_path(@event) do |f|
            = f.input :body, label: false
            = f.submit "Post", class: 'button'
        %ul
          - @event.posts.order('-id').each do |post|
            %li
              = image_tag post.user.avatar, class: 'avatar'
              .post
                .user
                  = link_to post.user.name, user_path(post.user)
                  - if @event.organizer == post.user
                    (organizer)
                  - elsif @event.organizer == post.user
                    (speaker)
                .body= markdown post.body