config/routes.rb
Dotplus::Application.routes.draw do

  root to: 'pages#home', constraints: { subdomain: /www|^$/ }
  root to: 'events#index', constraints: { subdomain: /.+/ }, as: :next_event

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :sponsors
    resources :users
    resources :locations
  end

  get 'auth/twitter/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'logout' => 'sessions#destroy'

  resources :sponsors
  resources :talks
  resources :events do
    resources :posts
    resources :attendees do
      collection do
        get :rsvp
      end
    end
  end
  resources :users, path: '/' do
    resources :posts
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_many :events

  def to_param
    "#{id} #{name}".parameterize
  end
end

app/controllers/admin/sponsors_controller.rb
module Admin
  class SponsorsController < BaseController
    def index
      @sponsors = Sponsor.all
    end

    def show
      @sponsor = Sponsor.find(params[:id])
    end

    def new
      @sponsor = Sponsor.new
    end

    def create
      @sponsor = Sponsor.new(sponsor_params)
      if @sponsor.save
        flash[:success] = "Created #{@sponsor.name}"
        redirect_to admin_sponsor_path(@sponsor)
      else
        render :new
      end
    end

    def edit
      @sponsor = Sponsor.find(params[:id])
    end

    def update
      @sponsor = Sponsor.find(params[:id])
      if @sponsor.update_attributes(sponsor_params)
        flash[:success] = "Updated #{@sponsor.name}"
        redirect_to admin_sponsor_path(@sponsor)
      else
        render :edit
      end
    end

    private
    def sponsor_params
      params.require(:sponsor).permit(:name)
    end
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def show
    @sponsor = Sponsor.find(params[:id])
  end
end

app/views/admin/sponsors/edit.html.haml
.row
  .columns.large-6
    = simple_form_for @sponsor, url: admin_sponsor_path(@sponsor) do |f|
      %fieldset
        %legend= @sponsor.name
        = f.input :name
        = f.button :submit

app/views/admin/sponsors/index.html.haml
.row
  .columns
    %ul
      - @sponsors.each do |sponsor|
        %li= link_to sponsor.name, admin_sponsor_path(sponsor)

app/views/admin/sponsors/new.html.haml
.row
  .columns.large-6
    = simple_form_for @sponsor, url: admin_sponsors_path do |f|
      %fieldset
        %legend New Sponsor
        = f.input :name
        = f.button :submit

app/views/admin/sponsors/show.html.haml
.row
  .columns
    %h1= @sponsor.name
    = link_to "Edit #{@sponsor.name}", edit_admin_sponsor_path(@sponsor), class: 'button'
    %h2 Events
    %ul
      - @sponsor.events.each do |event|
        %li= link_to event.start.to_date, admin_event_path(event)