config/routes.rb
Dotplus::Application.routes.draw do

  root to: 'pages#home', constraints: { subdomain: /www|^$/ }
  root to: 'events#index', constraints: { subdomain: /.+/ }, as: :next_event

  namespace :admin do
    root to: 'events#index'
    resources :events
    resources :sponsors
    resources :users
    resources :locations
  end

  get 'auth/twitter/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'logout' => 'sessions#destroy'

  resources :sponsors
  resources :talks
  resources :events do
    resources :posts
    resources :attendees do
      collection do
        get :rsvp
      end
    end
  end
  resources :users, path: '/' do
    resources :posts
  end
end

app/views/layouts/admin.html.haml
- content_for :content do
  .row
    .columns
      %ul.inline-list
        %li= link_to "Events", admin_events_path
        %li= link_to "Sponsors", admin_sponsors_path
        %li= link_to "Users", admin_users_path
  = yield
= render template: 'layouts/application'

app/views/layouts/application.html.haml
!!! 5
%head
  %meta{ charset: "utf-8" }
  %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? "#{yield(:title)} | dotplus" : "dotplus"

  = stylesheet_link_tag "application"
  = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Audiowide&subset=latin"
  = javascript_include_tag "application"
  = favicon_link_tag 'logo.png'
  = csrf_meta_tag

  %meta{ property: "fb:app_id", content: "444965515591609" }
  %meta{ property: "og:site_name", content: "dotplus" }
  - if content_for?(:facebook_meta)
    = yield(:facebook_meta)
  - else
    %meta{ property: "og:url", content: request.url }
    %meta{ property: "og:title", content: "dotplus" }

%body
  - flash.each do |key, msg|
    = content_tag :div, msg, class: "alert-box #{key}"
  %nav.top-bar
    %ul.title-area
      %li.name
        %h1= link_to "dotplus", root_url(subdomain: 'www')
      %li.toggle-topbar.menu-icon
        = link_to '#' do
          %span
    %section.top-bar-section
      %ul.left
        %li.divider
          - City.find_each do |city|
            %li= nav_city_link city: city.name, subdomain: city.subdomain
      %ul.right
        %li.divider
        - if current_user
          %li.has-dropdown
            = link_to user_path(current_user) do
              = image_tag current_user.avatar, height: 20, width: 20, class: 'avatar'
              = current_user.twitter
            %ul.dropdown
              - if current_user.admin?
                %li= link_to "Admin", admin_root_path
              - if current_user.talks.any?
                %li= link_to "Talks", talks_path
              %li= link_to "Logout", logout_path
        - else
          %li
            = link_to "/auth/twitter?redirect_to=#{request.url}" do
              = image_tag 'twitter-login.png'

  = content_for?(:content) ? yield(:content) : yield

  #footer
    .row
      .large-6.columns
        %ul.inline-list
          %li= link_to "@dickeyxxx", "/dickeyxxx"
          %li= link_to "@jumph4x", "/jumph4x"
          %li= link_to "@thebucknerlife", "/thebucknerlife"

  = javascript_include_tag "//platform.twitter.com/widgets.js"
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41061966-1', 'dotplus.io');
    ga('send', 'pageview');